CREATE TABLE customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    cpf        VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    income     DECIMAL                                 NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    zip_code   VARCHAR(255)                            NOT NULL,
    street     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_cpf UNIQUE (cpf);
ALTER TABLE customer
    ADD CONSTRAINT uc_customer_email UNIQUE (email);

CREATE TABLE credit
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    credit_code            UUID                                    NOT NULL,
    credit_value           DECIMAL                                 NOT NULL,
    day_first_installment  date                                    NOT NULL,
    number_of_installments INT                                     NOT NULL,
    status                 INT,
    customer_id            BIGINT,
    CONSTRAINT pk_credit PRIMARY KEY (id)
);

ALTER TABLE credit
    ADD CONSTRAINT uc_credit_creditcode UNIQUE (credit_code);
ALTER TABLE credit
    ADD CONSTRAINT FK_CREDIT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

INSERT INTO CUSTOMER (ID,FIRST_NAME,LAST_NAME,CPF,EMAIL,INCOME,PASSWORD,ZIP_CODE,STREET)
VALUES
    (1,'JOSE','SILVA','11111111111','josesilva@gmail',10000,'1234','14076380','MATINICO PRADO'),
    (2,'JOAO','SOUZA','22222222222','joaosouza@gmail',5000,'1234','14076060','JOSE LEITE FLORES');